config/routes.rb
Rails.application.routes.draw do
  

  root to:'home#index'

  devise_for :users, controllers: {
             
                   registrations: 'users/registrations',
                   }

  resources :users
  
                 	
  get 'home/index'

  get 'home/admin'

  get 'home/customer'

  get 'home/dealer'

  get 'home/production'

  get 'home/guest'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
<hr>
<small>
<center>
<a href="http://aquadynamics.eu/">Aqua Dynamics (Pvt) Ltd </a>
</small>
</center>

</div>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<%flash.each do |f| %>
		<%type=f[0].to_s.gsub('alert','error').gsub('notice','info')%>
			toastr['<%= type %>']('<%= f[1] %>');

			<%end%>
	</script>
<%end%>			

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <%if !current_user%> 
          <%= link_to 'ZoomSails', root_path, class: 'navbar-brand' %>
         <% elsif current_user.has_role? :guest%>
          <%= link_to 'ZoomSails', home_guest_path, class: 'navbar-brand' %>
         <% elsif current_user.has_role? :admin%> 
          <%= link_to 'ZoomSails', home_admin_path, class: 'navbar-brand' %>
         <% elsif current_user.has_role? :customer%> 
          <%= link_to 'ZoomSails', home_customer_path, class: 'navbar-brand' %>
         <% elsif current_user.has_role? :dealer%> 
          <%= link_to 'ZoomSails', home_dealer_path, class: 'navbar-brand' %>
         <% elsif current_user.has_role? :prodution%> 
          <%= link_to 'ZoomSails', home_production_path, class: 'navbar-brand' %> 
          <%end%>
        </div>
        
        
<div class="collapse navbar-collapse pull-right">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %> 
 

         <li><%= link_to "#{current_user.email.downcase} #{current_user.roles_name}", edit_user_registration_path %></li>
           <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

          <li><%= link_to 'Log Out',destroy_user_session_path, method: :delete%></li>
            
           
<% if current_user.has_role? :admin or current_user.has_role? :super_admin %>

         <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Settings <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'User Management', users_path%></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
        </li>    

<% elsif current_user.has_role? :dealer %>
         <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Settings <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'User Management', users_path%></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
        </li>  






</ul>
</div>
</div>
<% end %>
<% end %>















        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoomsailp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%= render 'layouts/navigation'%>

  <body>
 <%= render 'layouts/messages'%>
  <div class="container">
  
    <%= yield %>

  </div>
  

<%= render 'layouts/footer'%>
  </body>
</html>